#pragma once
// NOTE: YOU NEED TO SET THE CORRECT VALUES FOR THE BUTTONS

// MODEL: XBOX ONE 1708

enum CONTROLLER_BUTTON
{
    CONTROLLER_BUTTON_NONE = 0x0000,
    CONTROLLER_BUTTON_A = 0x0001,
    CONTROLLER_BUTTON_B = 0x0002,
    CONTROLLER_BUTTON_Y = 0x0004,
    CONTROLLER_BUTTON_X = 0x0008,
    CONTROLLER_BUTTON_RB = 0x0020,
    CONTROLLER_BUTTON_RT = 0x0080,
    CONTROLLER_BUTTON_LB = 0x0010,
    CONTROLLER_BUTTON_LT = 0x0040,
    // Click Sticks
    CONTROLLER_BUTTON_LSB = 0x0100,
    CONTROLLER_BUTTON_RSB = 0x0200,
};

enum CONTROLLER_DPAD
{
    CONTROLLER_DPAD_NONE = 0x00,
    CONTROLLER_DPAD_UP = 0x01,
    CONTROLLER_DPAD_DOWN = 0x02,
    CONTROLLER_DPAD_LEFT = 0x08,
    CONTROLLER_DPAD_RIGHT = 0x04
};

enum CONTROLLER_MISC_BUTTON
{
    CONTROLLER_MISC_BUTTON_NONE = 0x00,
    CONTROLLER_MISC_BUTTON_START = 0x04,
    CONTROLLER_MISC_BUTTON_BACK = 0x02,
    CONTROLLER_MISC_BUTTON_SPECIAL = 0x01,
};